"""Added columns: full_name, username, dob to users table

Revision ID: 08b84547f5ab
Revises: 693c5ee3969a
Create Date: 2023-01-15 23:48:54.245857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b84547f5ab'
down_revision = '693c5ee3969a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=32), nullable=False))
    op.add_column('users', sa.Column('dob', sa.Date(), nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'username')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
